#!/usr/bin/env bash
apt-get update
apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 81246-web-01 52.206.167.46:80 check\n\tserver 81246-web-02 100.24.238.12:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
